### ISSUE TITLE
Trinket link broken

### ISSUE THREAD

**Issue by rondDev** [hilmanski/freeStuffDev#823] opened 2023-03-07 14:32 UTC
The link to Trinket is broken due to the ref.

This link does not work: https://trinket.io/?ref=freeStuffDev
It returns a 403 Forbidden

If we remove the ref, it woks fine, like this: https://trinket.io/

**Comment by hilmanski** [comment] 2023-03-22 23:04
thanks @rondDev will see what can we do about it. 
As we intentionally and automatically put ref on every link

**Comment by rondDev** [comment] 2023-03-23 13:50
> and automatically put ref on every link

I am aware, just thought I'd let you know that it's an issue

**Comment by perpetualsquid** [comment] 2023-10-28 15:19
@hilmanski is this fixed or is anything further needed? I'm asking because the PR has been merged but the issue is still open. Happy to contribute if anything is needed.

**Closed** 2023-11-01 02:54 UTC
